name: Widget Registry Version Check

on:
  push:
    paths:
      - "widget_registry.json"
  pull_request:
    paths:
      - "widget_registry.json"

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for version changes
        id: check
        run: |
          git show ${{ github.event.before }}:widget_registry.json > old_widget_registry.json
          jq -r '.widgets[].version' widget_registry.json | sort > new_versions.txt
          jq -r '.widgets[].version' old_widget_registry.json | sort > old_versions.txt
          if ! diff -q old_versions.txt new_versions.txt ; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Make GET request if version changed
        if: steps.check.outputs.version_changed == 'true'
        run: |
          curl -k -X POST 'https://ceintegration-en-hub.ge-209890.almostinsided.com/thirdPartyWidget/registry/adobe-widgets/refresh'
